### ISSUE TITLE
Throwing an error if argument of decode is undefined

### ISSUE THREAD

**Issue by XxSven** [anonyco/FastestSmallestTextEncoderDecoder#10]
I think this polyfill behavior is different from the native version for the function decode of TextDecoder.
When using `new TextDecoder.decode();` with no argument :
This polyfill will throw a blocking error, whereas using the native one returns an empty string.

**Comment by anonyco** [comment]
You are correct. I shall fix this behavior right away. Thank you so much for bringing this to my attention.

~ Happy Coding!

**Comment by anonyco** [comment]
I have just pushed a series of commits that resolve this issue. Thank you so much.
